### ISSUE TITLE
Unable to load via TCL

### ISSUE THREAD

**Issue by ric79** [shmir/PyTestCenter#1]
Hello,
I'm trying to use your package.

Here there is my config:

```
C:>tclsh
% package require SpirentTestCenter
08:48:47.910 WARN  - Only 8.5.9 and 8.5.14 Tcl versions are officially supported
 from the 8.5 series.
4.73
%
------------------------------------
more "c:\Tcl85\lib\Spirent TestCenter Application\pkgIndex.tcl"
set vers "4.73"
package ifneeded SpirentTestCenterConformance 4.73 "[list set env(STC_CONFIGURATION_FILE) ctsbll.ini]; [list source [file join CTS_INSTALL_DIR SpirentTestCenter.tcl]]; [list package provide SpirentTestCenterConformance 4.73]"
package ifneeded SpirentTestCenter 4.73 [list source [file join "C:/Program Files (x86)/Spirent Communications/Spirent TestCenter 4.73/Spirent TestCenter Application" SpirentTestCenter.tcl]]
package ifneeded stc 4.73 [list source [file join "C:/Program Files (x86)/Spirent Communications/Spirent TestCenter 4.73/Spirent TestCenter Application" SpirentTestCenter.tcl]]
package ifneeded stclib 4.73 [list source [file join "C:/Program Files (x86)/Spirent Communications/Spirent TestCenter 4.73/Spirent TestCenter Application" stclib.tcl]]
------------------------------------
PATH: C:\Tcl85\bin;
      C:\Program Files (x86)\Spirent Communications\Spirent TestCenter 4.73\Spirent TestCenter Application;

```

That is my little program:
```
...
install_dir = 'C:/Tcl85/lib'
lab_server = ''

class StcSamples(unittest.TestCase):
    def test_setUp(self):
        super(StcSamples, self).setUp()
        logger = logging.getLogger('log')
        logger.setLevel('DEBUG')
        logger.addHandler(logging.StreamHandler(sys.stdout))
        api_wrapper = StcTclWrapper(logger, install_dir)
        self.stc = StcApp(logger, api_wrapper=api_wrapper)
        self.stc.connect(lab_server)
```

... and this is the error:

```
set dir  {C:/Tcl85/lib/Spirent TestCenter Application} 
	C:/Tcl85/lib/Spirent TestCenter Application
source  {C:/Tcl85/lib/Spirent TestCenter Application/pkgIndex.tcl} 
	
package require SpirentTestCenter
Error Occured while loading the Spirent Automation Internal Utility Library (couldn't load library "C:/Program Files (x86)/Spirent Communications/Spirent TestCenter 4.73/Spirent TestCenter Application/sTcl.dll": invalid argument).
E
======================================================================
ERROR: test_setUp (__main__.StcSamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/xxx02020/PycharmProjects/untitled4/PyTestCenter-master/ric.py", line 26, in test_setUp
    api_wrapper = StcTclWrapper(logger, install_dir)
  File "C:\Users\xxx02020\PycharmProjects\untitled4\PyTestCenter-master\testcenter\api\stc_tcl.py", line 24, in __init__
    self.ver = self.eval('package require SpirentTestCenter')
  File "C:\Python27\lib\site-packages\trafficgenerator\tgn_tcl.py", line 211, in eval
    self.rc = self.tcl_interp.eval(command)
  File "C:\Python27\lib\site-packages\trafficgenerator\tgn_tcl.py", line 89, in eval
    return self.tcl.eval(command)
TclError: invalid command name "stc_int::salGet
```

I tried also to add an "a=self.eval('puts $tcl_version')" before line 89 and it is printing 8.5

I don't understand what I'm missing...
Riccardo

**Comment by shmir** [comment]
Hi Riccardo,

Before we dive, I suggest you use stc_app.init_stc to get your StcApp
object.
I know the sample does not use it but this is better.

from trafficgenerator.tgn_utils import ApiType
from testcenter.stc_app import init_stc

self.stc = init_stc(ApiType.tcl, 'C:/Program Files (x86)/Spirent
Communications/Spirent TestCenter 4.73, 'optional lab server address')

BTW - if you are using lab server, consider using REST instead of TCL.

And last - there are additional code samples in the tests modules - take a
look.

Yoram

**Comment by ric79** [comment]
Unfortunately my TC has not the REST Api. :(

Tried to run test_base.py but the error is the same.

```
self = <trafficgenerator.tgn_tcl.TgnTk object at 0x0000000003F2C160>
command = 'package require SpirentTestCenter'

    def eval(self, command):
>       return self.tcl.eval(command)
E       TclError: invalid command name "stc_int::salGet"

```

**Comment by shmir** [comment]
OK...

You do not work lab server / session manager? That's the only way to get
REST.

I have encountered such failures before.
Usually it has to do with bad STC client installation.
You can try to remove and re-install STC on your machine.
Another option - what version of python r u using? STC Tcl does not work
with 3.x.

And if all fails - maybe you can try ApiType.python. It is less debug but
maybe will work for you. But you need STC license for that :(

Yoram

**Comment by ric79** [comment]
Ok... I will try to reinstall or beg for a REST license. Thanks

**Comment by shmir** [comment]
Well... try to get lab_server, it has many more advantages, both for manual
and automatic testing.
Spirent has a virtual version of the lab server, maybe its free?

**Comment by shmir** [comment]
2 years without an answer...
